export type ErrorCode =
  | "NETWORK_ERROR"
  | "VALIDATION_ERROR"
  | "UNAUTHORIZED"
  | "FORBIDDEN"
  | "NOT_FOUND"
  | "UNKNOWN_ERROR"
  | "CONFLICT"
  | "INTERNAL_SERVER_ERROR"
  | "TOKEN_EXPIRED"
  | "INVALID_TOKEN"
  | "LOCKED"
  | "SLOT_NOT_AVAILABLE"
  | "DATABASE_ERROR";