export const RELATIONS = [
  "",
  "FATHER",
  "MOTHER",
  "PARENT",
  "HUSBAND",
  "WIFE",
  "SPOUSE",
  "SON",
  "DAUGHTER",
  "CHILD",
  "BROTHER",
  "SISTER",
  "SIBLING",
  "GRANDFATHER",
  "GRANDMOTHER",
  "GRANDPARENT",
  "GRANDSON",
  "GRANDDAUGHTER",
  "GRANDCHILD",
  "UNCLE",
  "AUNT",
  "NEPHEW",
  "NIECE",
  "COUSIN",
  "FATHER_IN_LAW",
  "MOTHER_IN_LAW",
  "BROTHER_IN_LAW",
  "SISTER_IN_LAW",
  "SON_IN_LAW",
  "DAUGHTER_IN_LAW",
  "GUARDIAN",
  "RELATIVE",
  "FRIEND",
  "OTHER",
  "SELF"
] as const;

export const GENDER = ["MALE", "FEMALE", "OTHERS", "PREFER NOT TO SAY"] as const

export type RelationToPatient = typeof RELATIONS[number];

export const RELATIONSTOSCHEMA = [
  // "",
  "Father",
  "Mother",
  "Parent",
  "Husband",
  "Wife",
  "Spouse",
  "Son",
  "Daughter",
  "Child",
  "Brother",
  "Sister",
  "Sibling",
  "Grandfather",
  "Grandmother",
  "Grandparent",
  "Grandson",
  "Granddaughter",
  "Grandchild",
  "Uncle",
  "Aunt",
  "Nephew",
  "Niece",
  "Cousin",
  "Father_In_Law",
  "Mother_In_Law",
  "Brother_In_Law",
  "Sister_In_Law",
  "Son_In_Law",
  "Daughter_In_Law",
  "Guardian",
  "Relative",
  "Friend",
  "Other",
  "Self"
] as const;

export const BLOODGROUPS = ["A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-"]